### ISSUE TITLE
It seems spys.one has another encoding method in other pages

### ISSUE THREAD

**Issue by Kelaxon** [xanderdin/scrape.spys.one.proxies#1]
I worked on your `fill_enctab` and `calc_port` methods for quite a while. 😅
Because I always get this stuff, when running your code:

![image](https://user-images.githubusercontent.com/19503195/44946881-198e7180-ae37-11e8-935c-ca748e9af3e8.png)

Finally, I found that the `script` you used in decoding was like:

![image](https://user-images.githubusercontent.com/19503195/44946858-966d1b80-ae36-11e8-92bb-33c427f4ef17.png)

But In the page I was trying to crawl (http://spys.one/free-proxy-list/CN/), it turns out that the `script` is like:

![image](https://user-images.githubusercontent.com/19503195/44947009-1d22f800-ae39-11e8-9369-9bb95f086787.png)

I tried to imitate your solution, but this one is a sort of different. 
Do you have any idea? 😃

**Comment by xanderdin** [comment]
Ah, that's really unexpected for me that someone at all is interested in that code. Actually, it was a programming assignment task set for me by a company I applied for a job a few month ago. That code was working well for the assignment requirements back then. Never touched it again since then and now I'm barely remember what it is all about :)

**Comment by Kelaxon** [comment]
Oh, I see. 😂 I will try other proxy websites then. 
Thx for reply. 😀
